"""
ARP Evidence Level System
=========================

Defines 4-level evidence classification for ARP pipeline outputs.

Usage:
    from evidence_level import EvidenceLevel, add_evidence_level
    
    result = {
        "targets": [
            {
                "name": "FSP1",
                "evidence_level": EvidenceLevel.VALIDATED,
                "confidence_source": "Boltz-2 prediction",
                "validated_by": ["Nature 2025"]
            }
        ]
    }
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from datetime import datetime
import hashlib
import json


class EvidenceLevel(Enum):
    """
    4-level evidence classification for ARP outputs.
    
    REAL        - Actual experimental/clinical data
    VALIDATED   - Validated model/AI predictions  
    HEURISTIC   - Rule-based/heuristic output
    SIMULATED   - Simulation results (needs validation)
    """
    REAL = "real"
    VALIDATED = "validated"
    HEURISTIC = "heuristic"
    SIMULATED = "simulated"
    
    @property
    def priority(self) -> int:
        """Lower = more reliable"""
        return {"real": 0, "validated": 1, "heuristic": 2, "simulated": 3}[self.value]
    
    @property
    def label(self) -> str:
        return {
            "real": "🟢 Real Data",
            "validated": "🔵 Validated",
            "heuristic": "🟡 Heuristic",
            "simulated": "🔴 Simulated"
        }[self.value]


@dataclass
class Provenance:
    """
    Provenance metadata for any ARP output.
    """
    source: str
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    pipeline_version: str = "1.0.0"
    branch: str = ""
    commit_hash: str = ""
    input_config_hash: str = ""
    tools_used: List[str] = field(default_factory=list)
    literature_sources: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "source": self.source,
            "timestamp": self.timestamp,
            "pipeline_version": self.pipeline_version,
            "branch": self.branch,
            "commit_hash": self.commit_hash,
            "input_config_hash": self.input_config_hash,
            "tools_used": self.tools_used,
            "literature_sources": self.literature_sources
        }
    
    @classmethod
    def from_git(cls) -> "Provenance":
        """Create Provenance from current git state"""
        import subprocess
        try:
            branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).decode().strip()
            commit = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()[:8]
        except:
            branch = "unknown"
            commit = "unknown"
        return cls(
            source="Generated by ARP pipeline",
            branch=branch,
            commit_hash=commit
        )


@dataclass
class TargetEvidence:
    """Evidence for a single target"""
    name: str
    level: EvidenceLevel
    confidence_source: str
    validated_by: List[str] = field(default_factory=list)
    raw_data: Optional[str] = None
    provenance: Optional[Provenance] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "evidence_level": self.level.value,
            "confidence_source": self.confidence_source,
            "validated_by": self.validated_by,
            "evidence_label": self.level.label,
            "provenance": self.provenance.to_dict() if self.provenance else {}
        }


@dataclass
class CandidateEvidence:
    """Evidence for a candidate compound"""
    name: str
    level: EvidenceLevel
    target: str
    priority: str
    confidence_source: str
    ic50_nM: Optional[float] = None
    smiles: Optional[str] = None
    provenance: Optional[Provenance] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "evidence_level": self.level.value,
            "target": self.target,
            "priority": self.priority,
            "confidence_source": self.confidence_source,
            "ic50_nM": self.ic50_nM,
            "smiles": self.smiles,
            "evidence_label": self.level.label,
            "provenance": self.provenance.to_dict() if self.provenance else {}
        }


def add_evidence_level(target_dict: Dict, level: EvidenceLevel, 
                       confidence_source: str, validated_by: List[str] = None) -> Dict:
    """
    Add evidence level to a target dictionary.
    
    Args:
        target_dict: Target dict with 'name', etc.
        level: EvidenceLevel enum
        confidence_source: What generated this result
        validated_by: List of PMIDs, papers, etc.
    
    Returns:
        Updated dict with evidence fields
    """
    target_dict["evidence_level"] = level.value
    target_dict["evidence_label"] = level.label
    target_dict["confidence_source"] = confidence_source
    target_dict["validated_by"] = validated_by or []
    return target_dict


def format_evidence_summary(targets: List[Dict]) -> str:
    """
    Create a human-readable evidence summary.
    
    Args:
        targets: List of target dicts with evidence_level
    
    Returns:
        Markdown-formatted summary
    """
    counts = {"real": 0, "validated": 0, "heuristic": 0, "simulated": 0}
    for t in targets:
        lvl = t.get("evidence_level", "unknown")
        if lvl in counts:
            counts[lvl] += 1
    
    lines = ["## Evidence Summary", ""]
    lines.append(f"- 🟢 Real Data: {counts['real']}")
    lines.append(f"- 🔵 Validated: {counts['validated']}")
    lines.append(f"- 🟡 Heuristic: {counts['heuristic']}")
    lines.append(f"- 🔴 Simulated: {counts['simulated']}")
    
    return "\n".join(lines)


# Convenience function for marking results
def mark_real(data: Any, source: str) -> Dict:
    """Mark data as REAL evidence level"""
    return {
        "data": data,
        "evidence_level": EvidenceLevel.REAL.value,
        "source": source,
        "timestamp": datetime.utcnow().isoformat()
    }


def mark_validated(data: Any, confidence_source: str, validated_by: List[str] = None) -> Dict:
    """Mark data as VALIDATED evidence level"""
    return {
        "data": data,
        "evidence_level": EvidenceLevel.VALIDATED.value,
        "confidence_source": confidence_source,
        "validated_by": validated_by or [],
        "timestamp": datetime.utcnow().isoformat()
    }


def mark_heuristic(data: Any, rules_used: str) -> Dict:
    """Mark data as HEURISTIC evidence level"""
    return {
        "data": data,
        "evidence_level": EvidenceLevel.HEURISTIC.value,
        "rules_used": rules_used,
        "timestamp": datetime.utcnow().isoformat()
    }


def mark_simulated(data: Any, simulation_params: Dict) -> Dict:
    """Mark data as SIMULATED evidence level"""
    return {
        "data": data,
        "evidence_level": EvidenceLevel.SIMULATED.value,
        "simulation_params": simulation_params,
        "timestamp": datetime.utcnow().isoformat()
    }


if __name__ == "__main__":
    # Test
    prov = Provenance.from_git()
    print(f"Branch: {prov.branch}")
    print(f"Commit: {prov.commit_hash}")
    
    # Test target
    target = {
        "name": "FSP1",
        "mechanism": "Ferroptosis suppression"
    }
    target = add_evidence_level(
        target,
        EvidenceLevel.VALIDATED,
        "Boltz-2 structure prediction",
        ["Nature 2025", "PNAS 2025"]
    )
    print(f"\nTarget with evidence: {target}")
    
    # Test summary
    targets = [
        {"name": "FSP1", "evidence_level": "validated"},
        {"name": "SLC7A11", "evidence_level": "real"},
        {"name": "GPX4", "evidence_level": "heuristic"},
    ]
    print(f"\n{format_evidence_summary(targets)}")